# Generated by Django 5.2.1 on 2025-05-26 16:32

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_hub', '0004_empresa_arquivo_base_conhecimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('texto', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='data_hub.empresa')),
            ],
            options={
                'indexes': [models.Index(fields=['empresa'], name='knowledge_b_empresa_a83d4f_idx')],
            },
        ),
    ]
