# Generated by Django 5.2.1 on 2025-05-19 19:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_hub', '0003_calendarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow', models.CharField(max_length=255)),
                ('nome_deploy', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('prompt_text', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='data_hub.empresa')),
            ],
            options={
                'verbose_name_plural': 'Prompts',
                'db_table': 'hub_prompt_history',
                'indexes': [models.Index(fields=['empresa', 'workflow', 'nome_deploy', 'ativo'], name='hub_prompt__empresa_5af75e_idx')],
            },
        ),
    ]
