# Generated by Django 5.2.1 on 2025-05-19 19:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Workflows',
                'db_table': 'hub_workflows',
            },
        ),
        migrations.RenameIndex(
            model_name='prompt',
            new_name='hub_prompt__empresa_c91a41_idx',
            old_name='hub_prompt__empresa_5af75e_idx',
        ),
        migrations.AlterField(
            model_name='prompt',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='prompts_hub.workflow'),
        ),
    ]
