# Generated by Django 5.2.1 on 2025-05-26 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts_hub', '0002_workflow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorflowTestReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(help_text='Mensagem original recebida pelo assistente')),
                ('output', models.TextField(help_text='Resposta gerada pela IA')),
                ('if_approval', models.BooleanField(default=False, help_text='A IA aprovou ou não?')),
                ('ai_full_response', models.JSONField(help_text='JSON completo retornado pela IA')),
                ('reviewed', models.BooleanField(default=False, help_text='Já revisado por um humano?')),
                ('reviewer_comments', models.TextField(blank=True, null=True)),
                ('reviewer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(help_text='Fluxo de onde vem o output analisado', on_delete=django.db.models.deletion.CASCADE, related_name='test_reviews', to='prompts_hub.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
