# Generated by Django 5.2.1 on 2025-05-26 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0003_calendarios'),
        ('prompts_hub', '0003_worflowtestreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='worflowtestreview',
            name='empresa',
            field=models.ForeignKey(default='ee861b9a-c97c-4ccf-85b6-e1381bd5c1f4', help_text='Empresa de onde vem o output analisado', on_delete=django.db.models.deletion.CASCADE, related_name='test_reviews', to='data_hub.empresa'),
            preserve_default=False,
        ),
    ]
