# Generated by Django 5.2.1 on 2025-05-26 11:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0003_calendarios'),
        ('prompts_hub', '0004_worflowtestreview_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='input_schema',
            field=models.JSONField(blank=True, help_text='Define quais campos o modelo precisa coletar (com ou sem tipos)', null=True),
        ),
        migrations.CreateModel(
            name='PromptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_deploy', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('prompt_text', models.TextField()),
                ('input_schema', models.JSONField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=False)),
                ('version_number', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('criado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_hub.empresa')),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='prompts_hub.prompt')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prompts_hub.workflow')),
            ],
            options={
                'ordering': ['-criado_em'],
                'unique_together': {('original', 'version_number')},
            },
        ),
    ]
