# Generated by Django 5.2.1 on 2025-05-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts_hub', '0005_prompt_input_schema_prompthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='input_schema',
            field=models.JSONField(blank=True, help_text='Exemplo: {"fields": {"nome": {"type": "string"}, "data_nascimento": {"type": "date"}}}', null=True),
        ),
    ]
