# Generated by Django 5.2.1 on 2025-05-27 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts_hub', '0006_alter_prompt_input_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucesso_final', models.BooleanField(default=False, help_text='O objetivo final do usuário foi atingido? Ex: agendar, remarcar, etc.')),
                ('qualidade_respostas', models.IntegerField(choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')], default=3, help_text='Nota geral para as respostas da IA (completude, clareza, coerência)')),
                ('houve_ruidos', models.BooleanField(default=False, help_text='Houve partes da conversa onde a IA demonstrou ruído ou má interpretação?')),
                ('comentario_geral', models.TextField(blank=True, help_text='Comentários adicionais sobre o comportamento da IA no caso analisado', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(help_text='Usuário do sistema que realizou a revisão', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('test_review', models.ForeignKey(help_text='Thread de conversa testada com a IA', on_delete=django.db.models.deletion.CASCADE, related_name='human_reviews', to='prompts_hub.worflowtestreview')),
            ],
            options={
                'ordering': ['-criado_em'],
                'unique_together': {('reviewer', 'test_review')},
            },
        ),
    ]
