# Generated by Django 5.2.1 on 2025-05-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompts_hub', '0007_humanreview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='humanreview',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='humanreview',
            name='test_review',
        ),
    ]
