# Generated by Django 5.2.1 on 2025-05-27 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts_hub', '0008_alter_humanreview_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanreview',
            name='prompt_review',
            field=models.ForeignKey(default=0, help_text='Prompt que foi revisado manualmente', on_delete=django.db.models.deletion.CASCADE, related_name='human_reviews_from_prompt', to='prompts_hub.prompt'),
            preserve_default=False,
        ),
    ]
