#!/bin/bash
set -e;

if [ -n "${POSTGRES_NON_ROOT_USER:-}" ] && [ -n "${POSTGRES_NON_ROOT_PASSWORD:-}" ]; then
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE USER ${POSTGRES_NON_ROOT_USER} WITH PASSWORD '${POSTGRES_NON_ROOT_PASSWORD}';
        GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_NON_ROOT_USER};
        GRANT CREATE ON SCHEMA public TO ${POSTGRES_NON_ROOT_USER};
    EOSQL
fi

# Criar o banco da Evolution API
if [ -n "${EVOLUTION_POSTGRES_DB:-}" ]; then
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
        CREATE DATABASE ${EVOLUTION_POSTGRES_DB};
        GRANT ALL PRIVILEGES ON DATABASE ${EVOLUTION_POSTGRES_DB} TO ${POSTGRES_NON_ROOT_USER};
    EOSQL
    echo "Banco ${EVOLUTION_POSTGRES_DB} criado com sucesso!"
else
    echo "SETUP INFO: EVOLUTION_POSTGRES_DB não definido!"
fi
