# Generated by Django 5.2.1 on 2025-05-19 16:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('telefone_whatsapp', models.CharField(max_length=30, unique=True)),
                ('apikeybot', models.CharField(max_length=100, unique=True)),
                ('tokeninstance', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
                'db_table': 'hub_empresa',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('telefone_whatsapp', models.CharField(max_length=30, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('conversation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='data_hub.empresa')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'db_table': 'hub_clientes',
            },
        ),
    ]
