# Generated by Django 5.2.1 on 2025-05-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone_whatsapp',
            field=models.CharField(max_length=30),
        ),
    ]
