# Generated by Django 5.2.1 on 2025-05-19 17:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0002_alter_cliente_telefone_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendarios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calendar_name', models.CharField(max_length=100)),
                ('calendar_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_hub.empresa')),
            ],
            options={
                'db_table': 'hub_calendarios',
            },
        ),
    ]
