# Generated by Django 5.2.1 on 2025-05-26 16:16

import data_hub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0003_calendarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='arquivo_base_conhecimento',
            field=models.FileField(blank=True, null=True, upload_to=data_hub.models.caminho_upload_conhecimento),
        ),
    ]
