# Generated by Django 5.2.1 on 2025-05-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0004_empresa_arquivo_base_conhecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='qrcode_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
